name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Se ejecuta al hacer un push a la rama 'main'

jobs:
  build:
    runs-on: ubuntu-latest  # El entorno de ejecución es Ubuntu

    steps:
      # Paso 1: Clonar el repositorio
      - name: Check out repository
        uses: actions/checkout@v2

      # Paso 2: (Opcional) Copiar los archivos a la raíz del repositorio
      - name: Copy files to root
        run: |
          cp -r * ./  # Copiar todos los archivos a la raíz del repositorio

      # Paso 3: Configuración de Git y despliegue
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'GitHub Actions'  # Nombre del commit
          git config --global user.email 'actions@github.com'  # Correo del commit
          git add -A  # Añadir todos los archivos modificados
          git commit -m "Deployed with GitHub Actions"  # Crear un commit con el mensaje
          git push origin main  # Enviar los cambios a la rama 'main'
